### ISSUE TITLE
retarget 4x up test vector

### ISSUE THREAD

**Issue by prestwich** [summa-tx/bitcoin-spv#103]
New test vector: 
In `retargetAlgorithm`
Input should use blocks 66528, 68543, and 68544.
output is the difficulty of 68544

Should be able to get all the info from the bc.i rawblock endpoint
https://blockchain.info/rawblock/0000000000519051eb5f3c5943cdbc176a0eff4e1fbc3e08287bdb76299b8e5c

**Comment by ErinHales** [comment]
This doesn't give me the raw header.  Is there another way to get that?

**Comment by prestwich** [comment]
Add `?format=hex`

**Comment by ErinHales** [comment]
Here is what that gives me, but it's much longer than 80 bytes `01000000fb57c71ccd211b3de4ccc2e23b50a7cdb72aab91e60737b3a2bfdf030000000088a88ad9df68925e880e5d52b7e50cef225871c68b40a2cd0bca1084cd436037f388404cfd68011caeb1f8010301000000010000000000000000000000000000000000000000000000000000000000000000ffffffff0804fd68011c02b007ffffffff0100f2052a010000004341042cc9267553c65b462a51a554b8afeea9a9284cae14dfe3ddf337799781f5432692fc6e6b40e2ae19194b37f2e43a4fd7bcfba343ee7f2eff0a3745a8ade2a52eac000000000100000001fd962975aa2273ca57fb7a2873807fde30531d936fabaad31ffbcd4ce2a99449010000008c493046022100b4d36267fabcce8b2439ab5ba2ab7d468c23ca9d44c2b98d303275fbac73da6b022100d39267668bb23d502283a47cc0b5579cec59e8fd7c982f26ba1fd85f7afcd91d01410473958bd864555b1f3ae236df80e6442a714433315559fc3e0768c98ba39b3d37f898b953dfb5fe5332ba4b95b9f027c048c9867ff20031795ddacffc4f3c821dffffffff01404b4c00000000001976a9141f2341d54bbcffaa6bb989769ac91185d1fbff2a88ac000000000100000001a19ac3df4951b073d738e412b7562b816db65073e53eebfb66487045eb3e3200010000008c493046022100a0a1e3f6eead48c75ff05fc5e6dc5d6a49fe8628425477ba2c352c205821f307022100c74416ea0ebc81e7192377e3bc60b952c7ef05417b2685ea1437dccea468ff81014104fe1b3a5f0d60b60d30c1ef437decb6cd570e46198514103901bbc93cd45ed2d481cbb645cb775fde637cf13b87fbfbb8691a62d87f8c03b2fd67520ac125b3f5ffffffff0140420f00000000001976a914a8e236c585d5cd0de1f92aeee6634075fc945d3888ac00000000`

**Comment by prestwich** [comment]
That includes transactions. Take the first 80 bytes
