### ISSUE TITLE
Bitcoin outpoint length is not checked in `wpkhSpendSighash`

### ISSUE THREAD

**Issue by wadeAlexC** [summa-tx/bitcoin-spv#112]
#### Description

`CheckBitcoinSigs.wpkhSpendSighash` calculates the sighash of a Bitcoin transaction. Among its parameters, it accepts `bytes memory _outpoint`, which is a 36-byte UTXO id consisting of a 32-byte transaction hash and a 4-byte output index.

The function in question should not accept an `_outpoint` that is not 36-bytes, but no length check is made:

https://github.com/summa-tx/bitcoin-spv/blob/f5e4da091a1c97e6432c2d70eba434edb189f919/solidity/contracts/CheckBitcoinSigs.sol#L130-L159

#### Recommendation

Check that `_outpoint.length` is 36.

**Comment by prestwich** [comment]
I can't stop people from calling functions with bad inputs. GIGO.
