### ISSUE TITLE
Library contains multiple integer under-/overflows

### ISSUE THREAD

**Issue by wadeAlexC** [summa-tx/bitcoin-spv#113]
#### Description

The bitcoin-spv library allows for multiple integer under-/overflows while processing or converting potentially untrusted or user-provided data.

#### Examples

* `uint8` underflow `uint256(uint8(_e - 3))`
**Note**: `_header[75]` will throw consuming all gas if out of bounds while the majority of the library usually uses `slice(start, 1)` to handle this more gracefully.
 
https://github.com/summa-tx/bitcoin-spv/blob/f5e4da091a1c97e6432c2d70eba434edb189f919/solidity/contracts/BTCUtils.sol#L483-L494

* `uint8` overflow `uint256(uint8(_len + 8 + 1))`
**Note**: might allow a specially crafted output to return an invalid determineOutputLength <= 9.
**Note**: while type `VarInt` is implemented for inputs, it is not for the output length.

https://github.com/summa-tx/bitcoin-spv/blob/f5e4da091a1c97e6432c2d70eba434edb189f919/solidity/contracts/BTCUtils.sol#L295-L304

* `uint8` underflow `uint256(uint8(extractOutputScriptLen(_output)[0]) - 2)`

https://github.com/summa-tx/bitcoin-spv/blob/f5e4da091a1c97e6432c2d70eba434edb189f919/solidity/contracts/BTCUtils.sol#L366-L378

* `BytesLib` input validation multiple start+length overflow
**Note**: multiple occurrences. should check `start+length > start && bytes.length >= start+length`

https://github.com/summa-tx/bitcoin-spv/blob/f5e4da091a1c97e6432c2d70eba434edb189f919/solidity/contracts/BytesLib.sol#L246-L248

* `BytesLib` input validation multiple start overflow

https://github.com/summa-tx/bitcoin-spv/blob/f5e4da091a1c97e6432c2d70eba434edb189f919/solidity/contracts/BytesLib.sol#L280-L281

https://github.com/summa-tx/bitcoin-spv/blob/f5e4da091a1c97e6432c2d70eba434edb189f919/solidity/contracts/BytesLib.sol#L269-L270

https://github.com/summa-tx/bitcoin-spv/blob/f5e4da091a1c97e6432c2d70eba434edb189f919/solidity/contracts/BytesLib.sol#L246-L248

https://github.com/summa-tx/bitcoin-spv/blob/f5e4da091a1c97e6432c2d70eba434edb189f919/solidity/contracts/BytesLib.sol#L410-L412

#### Recommendation

We believe that a general-purpose parsing and verification library for bitcoin payments should be very strict when processing untrusted user input. With strict we mean, that it should rigorously validate provided input data and only proceed with the processing of the data if it is within a safe-to-use range for the method to return valid results. Relying on the caller to provide pre-validate data can be unsafe especially if the caller assumes that proper input validation is performed by the library.

Given the risk profile for this library, we recommend a conservative approach that balances for security instead of gas efficiency without relying on certain calls or instructions to throw on invalid input.

For this issue specifically, we recommend proper input validation and explicit type expansion where necessary to prevent values from wrapping or processing data for arguments that are not within a safe-to-use range.

**Comment by prestwich** [comment]
Is this an exhaustive list or should I expect more?

**Comment by prestwich** [comment]
Brief overview of the security impact of each one:

* `extractTarget` -- cannot underflow with valid Bitcoin headers. Invalid headers result in an extremely high target threshold. Difficulty calculation would produce 0. This is wontfix as it has no impact on a proving system

* `determineOutputLength` -- Possible a carefully constructed output script could have contained another "fake" output inside it.  #118 

* `extractHash` -- A malicious output could have returned arbitrary data of length 254 or 255 for the hash. #119

* `BytesLib` -- @ErinHales can you update these require statements

**Comment by wadeAlexC** [comment]
> Is this an exhaustive list or should I expect more?

This is what we have at the moment. We're mostly moving away from this library, but may circle back later.
