### ISSUE TITLE
Unnecessary logic in BytesLib.toBytes32()

### ISSUE THREAD

**Issue by wadeAlexC** [summa-tx/bitcoin-spv#115]
#### Description

The heavily used library function `BytesLib.toBytes32()` unnecessarily casts `_source` to `bytes` (same type) and creates a copy of the dynamic byte array to check it's length, while this can be done directly on the user-provided `bytes _source`.

#### Examples

https://github.com/summa-tx/bitcoin-spv/blob/f5e4da091a1c97e6432c2d70eba434edb189f919/solidity/contracts/BytesLib.sol#L399-L408

#### Recommendation

```solidity
function toBytes32(bytes memory _source) pure internal returns (bytes32 result) {
        if (_source.length == 0) {
            return 0x0;
        }

        assembly {
            result := mload(add(_source, 32))
        }
    }
```

**Comment by prestwich** [comment]
Thanks, I believe this is a holdover from an older solidity version in the vendored dep.
