### ISSUE TITLE
Redundant functionality in BTCUtils

### ISSUE THREAD

**Issue by wadeAlexC** [summa-tx/bitcoin-spv#116]
#### Description

The library exposes redundant implementations of bitcoins double `sha256`.

#### Examples

* solidity native implementation with an overzealous type correction #16 
https://github.com/summa-tx/bitcoin-spv/blob/f5e4da091a1c97e6432c2d70eba434edb189f919/solidity/contracts/BTCUtils.sol#L110-L116

* assembly implementation
**Note** this implementation does not handle errors when staticcall'ing the precompiled `sha256` contract (private chains). 
https://github.com/summa-tx/bitcoin-spv/blob/f5e4da091a1c97e6432c2d70eba434edb189f919/solidity/contracts/BTCUtils.sol#L118-L129

#### Recommendation

We recommend providing only one implementation for calculating the double `sha256` as maintaining two interfaces for the same functionality is not desirable. Furthermore, even though the assembly implementation is saving gas, we recommend keeping the language provided implementation.

**Comment by prestwich** [comment]
This is a low-level toolkit. We'd like the caller to make their own decisions about gas and legibility. This is the same reason we provided Delegate versions of each contract.
