### ISSUE TITLE
Overhaul testing

### ISSUE THREAD

**Issue by prestwich** [summa-tx/bitcoin-spv#120]
Quality of life improvements to testing:

- [x] Update golang tests to use strongly typed cases instead of the messy type assertions
- [x] Differentiate error messages in `testVectors.json`. E.g. ALWAYS use `solidityError` and `goError` and `jsError` instead of always shoving them into `errorMessage`
- [x] Add comments  to errors in `testVectors.json`

**Comment by ErinHales** [comment]
To clarify, what is the purpose of adding comments in`testVectors.json`? Are they just for our understanding of what the error means and what we are trying to test?

**Comment by prestwich** [comment]
For maintainability. So that next time we have to go wade through that file, we know what's what
