### ISSUE TITLE
Remove redundant BE/LE elements from structs and serialization format

### ISSUE THREAD

**Issue by prestwich** [summa-tx/bitcoin-spv#132]

**Comment by ErinHales** [comment]
So if I understand right, I would take ```// HeaderFromRaw builds a BitcoinHeader from a raw bytestring and height
func HeaderFromRaw(raw RawHeader, height uint32) BitcoinHeader {
	digestLE := Hash256(raw[:])
	digestBE := ReverseHash256Endianness(digestLE)
	prevhashLE := ExtractPrevBlockHashLE(raw)
	prevhashBE := ReverseHash256Endianness(prevhashLE)
	merkleRootLE := ExtractMerkleRootLE(raw)
	merkleRootBE := ReverseHash256Endianness(merkleRootLE)

	return BitcoinHeader{
		raw,
		digestBE,
		digestLE,
		height,
		prevhashBE,
		prevhashLE,
		merkleRootBE,
		merkleRootLE,
	}
}``` and change it to ```// HeaderFromRaw builds a BitcoinHeader from a raw bytestring and height
func HeaderFromRaw(raw RawHeader, height uint32) BitcoinHeader {
	digest := Hash256(raw[:])
	prevhash := ExtractPrevBlockHashLE(raw)
	merkleRoot := ExtractMerkleRootLE(raw)

	return BitcoinHeader{
		raw,
		digest,
		height,
		prevhash,
		merkleRoot,
	}
}``` and then change the BitcoinHeader type appropriately?  I'd probably have to also add a note that these values are LE.

**Comment by prestwich** [comment]
yes, but it needs to be done for all languages
