### ISSUE TITLE
v2.0.0 wishlist

### ISSUE THREAD

**Issue by prestwich** [summa-tx/bitcoin-spv#19]
- [x] Use truffle
- [x] Change merkle proof index to be 0-indexed
- [x] ~Add new arg format to ValidateSPV (version, vin, vout, locktime)~ rewrite ValidateSPV
- [x] Add tooling for working with vin/vout
- [x] Add `isLegacy` tooling
- [x] https://github.com/keep-network/bitcoin-spv/pull/1/
- [x] dual visibility of all methods (internal for `jump` and public for `delegatecall`)
- [x] ~Make unsafe versions of methods with `require` statements~ remove unnecessary require statements

**Comment by prestwich** [comment]
- [ ] so many tests

**Comment by nkuba** [comment]
`validateHeaderChain` returns values from `1` to `3` in case of errors. Can we change it to bubble up an error?

https://github.com/summa-tx/bitcoin-spv/blob/a51fc8457b6dd0166e7a09149fc897e9e1a783ff/contracts/ValidateSPV.sol#L156

`1`, `2`, `3` seems like valid values for a case when the difficulty for blocks drops to `1` (it happens quite often on testnet).
