### ISSUE TITLE
The library doesn't work for other UTXO chain in rust

### ISSUE THREAD

**Issue by Milerius** [summa-tx/bitcoin-spv#221]
Hello, I was checking this library to use it in <https://github.com/KomodoPlatform/atomicDEX-API>

Our block header look like this: <https://github.com/KomodoPlatform/atomicDEX-API/blob/dc9e4c32fe1640091a962d0575eb9db45f91a6ce/mm2src/mm2_bitcoin/chain/src/block_header.rs#L81>

I'm unable to validate a block header for <https://rick.explorer.dexstats.info/block/0b9e313b71f56d60353137042d8810f3b35004f5451b2a138ba9dfe3b5bf13b4> because the hash digest will be incorrect since <https://github.com/summa-tx/bitcoin-spv/blob/fb2a61e7a941d421ae833789d97ed10d2ad79cfe/rust/src/std_types.rs#L24> is a hard-coded 80 bytes header.

Do you plan to switch to a Vec<u8> in order to support different UTXO headers?

Otherwise I'm basically thinking about inspiring from this library to write our own validation, I guess I will have the same kind of problem for difficulty that change between UTXO chains.

Thanks for your library, it's great!

**Comment by prestwich** [comment]
we have no plans to extend `bitcoin-spv` for other chains. It's out of scope for the project. We also have a library for off-chain utilities [here](https://github.com/summa-tx/bitcoins-rs/) is intended to be extended for other networks, but may not be suitable for on-chain execution

**Comment by Milerius** [comment]
Oh thanks for letting me know! Wish you a good day!
