### ISSUE TITLE
retarget algorithm missing equal target implementation

### ISSUE THREAD

**Issue by Pl8tinium** [summa-tx/bitcoin-spv#253]
For the various implementations of the retarget algorithm an essential piece of code is missing so that it can successfully calculate the difficulty for block heights that dont need adjustments like block height 0-2016

https://github.com/bitcoin/bitcoin/blob/master/src/pow.cpp#L68

if that "if clause" is implemented you get the correct difficulty back for retarget heights like 2016

**Comment by prestwich** [comment]
this is an SPV library. it is never safe to use SPV for blocks with minimum or near-minimum difficulty

**Comment by Geo25rey** [comment]
Fair point, but the doesn't change the fact that all implementations of the retarget algorithm are incorrect. It can pose a major security risk when replaying historical blocks and can allow major shifts in difficulty requirements down the line.

**Comment by prestwich** [comment]
it cannot pose a security risk, as SPV near the minimum difficulty is never secure. SPV also never replays historical blocks. please do not use this library if you do not understand how SPV works
