### ISSUE TITLE
Write tests for BTCUtils.js

### ISSUE THREAD

**Issue by dominiquejane** [summa-tx/bitcoin-spv#26]
Missing tests for:
- [x] extractInputTxIdLE
- [x] extracInputTxId
- [x] extractTxIndexLE
- [x] extractTxIndex

Other methods that are not tested, but are used by other methods that pass their own tests, so I'm not sure if tests for these are necessary:
- [x] extractMerkleRootLE, is used by extractMerkleRootBE, which passes
- [x] calculateDifficulty, is used by extractTimestamp, which passes
- [x] extractPrevBlockLE, is used by extractPrevBlockBE, which passes
- [x] extractTimestampLE, is used by extractTimestamp, which passes
- [x] hash256MerkleStep, is used by verifyHash256Merkle, which passes

**Comment by prestwich** [comment]
`extractInputTxIdLE`:
input: `0x1746bd867400f3494b8f44c24b83e1aa58c4f0ff25b4a61cffeffd4bc0f9ba300000000001eeffffffff`
output: 0x1746bd867400f3494b8f44c24b83e1aa58c4f0ff25b4a61cffeffd4bc0f9ba30

`extracInputTxId`
input: `0x1746bd867400f3494b8f44c24b83e1aa58c4f0ff25b4a61cffeffd4bc0f9ba300000000001eeffffffff`
output: `0x30baf9c04bfdefff1ca6b425fff0c458aae1834bc2448f4b49f3007486bd4617`


`extractTxIndexLE`
input: `0x1746bd867400f3494b8f44c24b83e1aa58c4f0ff25b4a61cffeffd4bc0f9ba300000000001eeffffffff` 
output `0xffffffff`

`extractTxIndex`
input: `0x1746bd867400f3494b8f44c24b83e1aa58c4f0ff25b4a61cffeffd4bc0f9ba300000000001eeffffffff` 
output: `4294967295`

**Comment by prestwich** [comment]
don't worry about the ones used in other tests

**Comment by dominiquejane** [comment]
@james can you double check the output for `extractTxIndexLE` (the third one)

**Comment by prestwich** [comment]
ack, ya. copy past error. should be `00000000`

**Comment by dominiquejane** [comment]
@prestwich does correcting the third output affect the fourth output?

**Comment by prestwich** [comment]
Yes, it should also be `0`
