### ISSUE TITLE
Remove `hex` dependency from `bitcoin_spv.go`

### ISSUE THREAD

**Issue by prestwich** [summa-tx/bitcoin-spv#84]
I don't like that we rely on string (de)serialization in bitcoin spv. we should figure out alternative elegant ways of doing this

**Comment by ErinHales** [comment]
I've been trying to figure this one out.  In the test, we are trying to convert a very large number, but `sdk.newUint()` only accepts `uint64`.  So basically, I think I can convert it to the right number, but then I can't convert the type to sdk uint.

**Comment by prestwich** [comment]
something like:
```
myInt := new(big.Int).SetBytes(rawBytes)
myUint := sdk.NewUintFromBigInt(myInt)
```

**Comment by prestwich** [comment]
also, just noticed this:

```
// BytesToBigInt converts a bytestring to a cosmos-sdk Int
func BytesToBigInt(b []byte) sdk.Uint {
	ret := sdk.NewUintFromString("0x" + hex.EncodeToString(b))
	return ret
}

// BytesToBigUint converts a bytestring of up to 32 bytes to a cosmos sdk uint
func BytesToBigUint(b []byte) sdk.Uint {
	ret := sdk.NewUintFromString("0x" + hex.EncodeToString(b))
	return ret
}
```

these functions are identical :rofl:

**Comment by ErinHales** [comment]
Lol, I noticed that too 🤣

**Comment by ErinHales** [comment]
Are we still wanting to keep `bytesToBigInt`?  `BytesToBigUint` is working just fine, but apparently this test value (`"0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"`) is too large to use in `sdk.NewIntFromBigInt()` so `BytesToBigInt` is not passing tests.

**Comment by prestwich** [comment]
I think we can drop `bytesToBigInt`
