### ISSUE TITLE
Running into error with test txn

### ISSUE THREAD

**Issue by tarrencev** [summa-tx/bitcoin-spv#9]
Hi! Thanks for the interesting library. I'm attempting to run as detailed in the readme but running into an issue.

When running:
`pipenv run python scripts/merkle.py 10e3eaed1ef21787944f0d151a1a6553397e2ee4074887e344a112e13f22b70b`

I get:
`Tx is too large. Expect less than 100kB. Got: 153762 bytes`

Am I doing this correctly?

I'm using Python 3.6.6 on osx

Thanks!

**Comment by prestwich** [comment]
Huh. I thought I disabled that check. One of the txns in the same block as your tx is unexpectedly large.

@rrybarczyk can you make a PR for riemann that removes this check in `tx.py`?

**Comment by rrybarczyk** [comment]
@prestwich done. bumped to v1.1.2

**Comment by prestwich** [comment]
@tarrencev I just pushed a commit. I was able to run your command locally :+1:. Please pull latest, run `pipenv install` and then try again

**Comment by tarrencev** [comment]
Confirming it works now! Thanks a lot 💯
